export interface Template {
  id: string;
  name: string;
  category: 'minimal' | 'professional' | 'student' | 'creator' | 'developer' | 'photographer';
  description: string;
  isPro: boolean;
  colors: {
    primary: string;
    secondary: string;
    background: string;
    text: string;
    accent?: string;
  };
  font: string;
  layout: 'centered' | 'split' | 'asymmetric' | 'grid' | 'magazine' | 'immersive';
  features?: string[];
}

export const templates: Template[] = [
  // ========== MINIMAL TEMPLATES (6) ==========
  {
    id: 'clean-slate',
    name: 'Clean Slate',
    category: 'minimal',
    description: 'A beautifully simple design that lets your content shine',
    isPro: false,
    colors: { primary: '#1a1a1a', secondary: '#666666', background: '#ffffff', text: '#1a1a1a' },
    font: 'Inter',
    layout: 'centered',
  },
  {
    id: 'noir',
    name: 'Noir',
    category: 'minimal',
    description: 'Elegant dark theme with sophisticated typography',
    isPro: false,
    colors: { primary: '#ffffff', secondary: '#888888', background: '#0a0a0a', text: '#ffffff' },
    font: 'Playfair Display',
    layout: 'centered',
  },
  {
    id: 'zen',
    name: 'Zen',
    category: 'minimal',
    description: 'Peaceful and calming with soft tones',
    isPro: false,
    colors: { primary: '#4a5568', secondary: '#718096', background: '#f7fafc', text: '#2d3748' },
    font: 'Lora',
    layout: 'centered',
  },
  {
    id: 'paper',
    name: 'Paper',
    category: 'minimal',
    description: 'Clean typographic focus with newspaper-inspired layout',
    isPro: false,
    colors: { primary: '#1f2937', secondary: '#6b7280', background: '#fafaf9', text: '#1f2937' },
    font: 'Crimson Pro',
    layout: 'magazine',
  },
  {
    id: 'essence',
    name: 'Essence',
    category: 'minimal',
    description: 'Ultra-minimalist with bold accents',
    isPro: true,
    colors: { primary: '#dc2626', secondary: '#374151', background: '#ffffff', text: '#111827', accent: '#dc2626' },
    font: 'Helvetica Neue',
    layout: 'asymmetric',
    features: ['parallax', 'reveal-on-scroll', 'smooth-scroll'],
  },
  {
    id: 'mono',
    name: 'Mono',
    category: 'minimal',
    description: 'Monochromatic elegance with dramatic typography',
    isPro: true,
    colors: { primary: '#18181b', secondary: '#52525b', background: '#fafafa', text: '#09090b' },
    font: 'Space Mono',
    layout: 'grid',
    features: ['text-reveal', 'cursor-effects', 'smooth-scroll'],
  },

  // ========== PROFESSIONAL TEMPLATES (6) ==========
  {
    id: 'executive',
    name: 'Executive',
    category: 'professional',
    description: 'Perfect for business professionals and executives',
    isPro: false,
    colors: { primary: '#2563eb', secondary: '#3b82f6', background: '#ffffff', text: '#1e293b' },
    font: 'Source Sans Pro',
    layout: 'split',
  },
  {
    id: 'resume-pro',
    name: 'Resume Pro',
    category: 'professional',
    description: 'Showcase your career achievements with style',
    isPro: true,
    colors: { primary: '#059669', secondary: '#10b981', background: '#ffffff', text: '#1f2937', accent: '#059669' },
    font: 'Roboto',
    layout: 'split',
    features: ['animated-timeline', 'skill-bars', 'hover-cards'],
  },
  {
    id: 'corporate',
    name: 'Corporate',
    category: 'professional',
    description: 'Clean and professional for the modern workplace',
    isPro: false,
    colors: { primary: '#0f172a', secondary: '#475569', background: '#f8fafc', text: '#0f172a' },
    font: 'Open Sans',
    layout: 'centered',
  },
  {
    id: 'consultant',
    name: 'Consultant',
    category: 'professional',
    description: 'Authority-building layout for consultants and experts',
    isPro: false,
    colors: { primary: '#1e3a5f', secondary: '#3b82f6', background: '#ffffff', text: '#1e3a5f' },
    font: 'Merriweather',
    layout: 'magazine',
  },
  {
    id: 'prestige',
    name: 'Prestige',
    category: 'professional',
    description: 'Premium executive presence with gold accents',
    isPro: true,
    colors: { primary: '#b8860b', secondary: '#1a1a2e', background: '#0d0d1a', text: '#f0f0f0', accent: '#d4af37' },
    font: 'Cormorant Garamond',
    layout: 'immersive',
    features: ['gold-shimmer', 'parallax', 'fade-sections', 'hover-glow'],
  },
  {
    id: 'ceo',
    name: 'CEO',
    category: 'professional',
    description: 'C-suite level presentation with dynamic animations',
    isPro: true,
    colors: { primary: '#0a192f', secondary: '#64ffda', background: '#0a192f', text: '#ccd6f6', accent: '#64ffda' },
    font: 'IBM Plex Sans',
    layout: 'asymmetric',
    features: ['morphing-shapes', 'scroll-animations', 'magnetic-cursor', 'particle-bg'],
  },

  // ========== STUDENT TEMPLATES (5) ==========
  {
    id: 'campus',
    name: 'Campus',
    category: 'student',
    description: 'Ideal for students and recent graduates',
    isPro: false,
    colors: { primary: '#8b5cf6', secondary: '#a78bfa', background: '#ffffff', text: '#1f2937' },
    font: 'Nunito',
    layout: 'centered',
  },
  {
    id: 'scholar',
    name: 'Scholar',
    category: 'student',
    description: 'Academic-focused with publications and research sections',
    isPro: false,
    colors: { primary: '#0891b2', secondary: '#22d3ee', background: '#ffffff', text: '#164e63' },
    font: 'Merriweather',
    layout: 'magazine',
  },
  {
    id: 'grad',
    name: 'Grad',
    category: 'student',
    description: 'Fresh and modern for new graduates',
    isPro: true,
    colors: { primary: '#7c3aed', secondary: '#a855f7', background: '#faf5ff', text: '#4c1d95', accent: '#c084fc' },
    font: 'Quicksand',
    layout: 'grid',
    features: ['confetti-effect', 'animated-cards', 'gradient-text'],
  },
  {
    id: 'thesis',
    name: 'Thesis',
    category: 'student',
    description: 'Academic portfolio for researchers',
    isPro: false,
    colors: { primary: '#334155', secondary: '#64748b', background: '#f8fafc', text: '#1e293b' },
    font: 'PT Serif',
    layout: 'magazine',
  },
  {
    id: 'future',
    name: 'Future',
    category: 'student',
    description: 'Bold and innovative for ambitious graduates',
    isPro: true,
    colors: { primary: '#06b6d4', secondary: '#8b5cf6', background: '#020617', text: '#f1f5f9', accent: '#22d3ee' },
    font: 'Outfit',
    layout: 'immersive',
    features: ['aurora-bg', 'floating-elements', 'scroll-morph', 'glow-effects'],
  },

  // ========== CREATOR TEMPLATES (6) ==========
  {
    id: 'influencer',
    name: 'Influencer',
    category: 'creator',
    description: 'Bold and eye-catching for content creators',
    isPro: false,
    colors: { primary: '#ec4899', secondary: '#f472b6', background: '#ffffff', text: '#1f2937' },
    font: 'Poppins',
    layout: 'grid',
  },
  {
    id: 'streamer',
    name: 'Streamer',
    category: 'creator',
    description: 'Gaming and streaming focused with dynamic elements',
    isPro: true,
    colors: { primary: '#9333ea', secondary: '#c084fc', background: '#0f0f23', text: '#ffffff', accent: '#ff006e' },
    font: 'Orbitron',
    layout: 'immersive',
    features: ['neon-glow', 'scanline-effect', 'hover-glitch', 'animated-gradient'],
  },
  {
    id: 'youtuber',
    name: 'YouTuber',
    category: 'creator',
    description: 'Video-centric design for content creators',
    isPro: false,
    colors: { primary: '#ef4444', secondary: '#f87171', background: '#ffffff', text: '#1f2937' },
    font: 'Montserrat',
    layout: 'grid',
  },
  {
    id: 'podcast',
    name: 'Podcast',
    category: 'creator',
    description: 'Audio-focused layout for podcasters',
    isPro: false,
    colors: { primary: '#f59e0b', secondary: '#fbbf24', background: '#1c1917', text: '#fafaf9' },
    font: 'DM Sans',
    layout: 'split',
  },
  {
    id: 'superstar',
    name: 'Superstar',
    category: 'creator',
    description: 'Celebrity-grade presence with stunning visuals',
    isPro: true,
    colors: { primary: '#f472b6', secondary: '#fb923c', background: '#000000', text: '#ffffff', accent: '#fbbf24' },
    font: 'Bebas Neue',
    layout: 'immersive',
    features: ['smoke-effect', 'parallax-3d', 'video-bg', 'hover-morph', 'scroll-reveal'],
  },
  {
    id: 'vibes',
    name: 'Vibes',
    category: 'creator',
    description: 'Aesthetic Gen-Z style with gradient magic',
    isPro: true,
    colors: { primary: '#a855f7', secondary: '#06b6d4', background: '#faf5ff', text: '#1e1b4b', accent: '#f472b6' },
    font: 'Plus Jakarta Sans',
    layout: 'asymmetric',
    features: ['gradient-mesh', 'floating-shapes', 'blur-cards', 'spring-animations'],
  },

  // ========== DEVELOPER TEMPLATES (6) ==========
  {
    id: 'devfolio',
    name: 'DevFolio',
    category: 'developer',
    description: 'Showcase your projects with code-inspired aesthetics',
    isPro: false,
    colors: { primary: '#22c55e', secondary: '#4ade80', background: '#0d1117', text: '#e6edf3' },
    font: 'JetBrains Mono',
    layout: 'grid',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    category: 'developer',
    description: 'Command-line inspired minimal developer portfolio',
    isPro: false,
    colors: { primary: '#10b981', secondary: '#34d399', background: '#111827', text: '#f3f4f6' },
    font: 'Fira Code',
    layout: 'centered',
  },
  {
    id: 'hacker',
    name: 'Hacker',
    category: 'developer',
    description: 'Matrix-inspired dark theme for tech enthusiasts',
    isPro: true,
    colors: { primary: '#00ff00', secondary: '#22c55e', background: '#000000', text: '#00ff00', accent: '#00ff00' },
    font: 'Source Code Pro',
    layout: 'centered',
    features: ['matrix-rain', 'typing-effect', 'terminal-cursor', 'glitch-text'],
  },
  {
    id: 'stack',
    name: 'Stack',
    category: 'developer',
    description: 'Tech stack focused with language badges',
    isPro: false,
    colors: { primary: '#3b82f6', secondary: '#60a5fa', background: '#1e293b', text: '#f1f5f9' },
    font: 'Inter',
    layout: 'grid',
  },
  {
    id: 'github',
    name: 'GitHub Style',
    category: 'developer',
    description: 'Contribution-graph inspired portfolio',
    isPro: false,
    colors: { primary: '#238636', secondary: '#3fb950', background: '#0d1117', text: '#c9d1d9' },
    font: 'Segoe UI',
    layout: 'magazine',
  },
  {
    id: 'neuron',
    name: 'Neuron',
    category: 'developer',
    description: 'AI/ML focused with neural network animations',
    isPro: true,
    colors: { primary: '#818cf8', secondary: '#c084fc', background: '#030712', text: '#e2e8f0', accent: '#6366f1' },
    font: 'Space Grotesk',
    layout: 'immersive',
    features: ['neural-network-bg', 'data-flow', 'hover-nodes', 'pulse-effects', 'scroll-parallax'],
  },

  // ========== PHOTOGRAPHER TEMPLATES (6) ==========
  {
    id: 'gallery',
    name: 'Gallery',
    category: 'photographer',
    description: 'Let your visual work take center stage',
    isPro: false,
    colors: { primary: '#f59e0b', secondary: '#fbbf24', background: '#ffffff', text: '#1f2937' },
    font: 'Cormorant Garamond',
    layout: 'grid',
  },
  {
    id: 'aperture',
    name: 'Aperture',
    category: 'photographer',
    description: 'Cinematic layout with immersive image presentation',
    isPro: true,
    colors: { primary: '#ef4444', secondary: '#f87171', background: '#18181b', text: '#fafafa', accent: '#ef4444' },
    font: 'Lora',
    layout: 'immersive',
    features: ['lightbox', 'image-zoom', 'fade-scroll', 'dramatic-reveal'],
  },
  {
    id: 'portfolio-x',
    name: 'Portfolio X',
    category: 'photographer',
    description: 'Modern grid-based layout for visual artists',
    isPro: false,
    colors: { primary: '#6366f1', secondary: '#818cf8', background: '#ffffff', text: '#1e1b4b' },
    font: 'DM Sans',
    layout: 'grid',
  },
  {
    id: 'studio',
    name: 'Studio',
    category: 'photographer',
    description: 'Clean gallery with category filtering',
    isPro: false,
    colors: { primary: '#171717', secondary: '#525252', background: '#fafafa', text: '#171717' },
    font: 'Manrope',
    layout: 'grid',
  },
  {
    id: 'lens',
    name: 'Lens',
    category: 'photographer',
    description: 'Full-screen hero images with minimal distractions',
    isPro: false,
    colors: { primary: '#a3a3a3', secondary: '#737373', background: '#0a0a0a', text: '#fafafa' },
    font: 'Libre Baskerville',
    layout: 'immersive',
  },
  {
    id: 'exposure',
    name: 'Exposure',
    category: 'photographer',
    description: 'Magazine-quality presentation with scroll animations',
    isPro: true,
    colors: { primary: '#fbbf24', secondary: '#f59e0b', background: '#000000', text: '#ffffff', accent: '#fbbf24' },
    font: 'Playfair Display',
    layout: 'immersive',
    features: ['image-reveal', 'parallax-gallery', 'smooth-scroll', 'cursor-follow', 'split-screen'],
  },
];

export const categories = [
  { id: 'all', name: 'All Templates', color: 'from-gray-600 to-gray-800', icon: '✨' },
  { id: 'minimal', name: 'Minimal', color: 'from-gray-600 to-gray-800', icon: '◻️' },
  { id: 'professional', name: 'Professional', color: 'from-blue-600 to-blue-800', icon: '💼' },
  { id: 'student', name: 'Student', color: 'from-violet-600 to-purple-800', icon: '🎓' },
  { id: 'creator', name: 'Creator', color: 'from-pink-500 to-rose-600', icon: '🎬' },
  { id: 'developer', name: 'Developer', color: 'from-emerald-500 to-teal-700', icon: '💻' },
  { id: 'photographer', name: 'Photographer', color: 'from-amber-500 to-orange-600', icon: '📷' },
];
